# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 08:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facebookapp', '0003_auto_20170809_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_final',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile_final',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
