# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facebookapp', '0004_auto_20170809_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_final',
            old_name='profile',
            new_name='profile1',
        ),
        migrations.RenameField(
            model_name='profile_final',
            old_name='id',
            new_name='profile_id',
        ),
    ]
