# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 08:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Facebookapp', '0005_auto_20170809_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_final',
            name='profile1',
        ),
        migrations.RemoveField(
            model_name='profile_final',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='profile_final',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile_final',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
